### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by SUPERCILEX** [SouthEugeneRoboticsTeam/PowerUp-2018#50]
- [x] See what happens if we bump up path velocity
- [x] Right to left scale path doesn't lift to switch
- [x] Figure out fishtailing on field cross paths

**Comment by SUPERCILEX** [comment]
Yay!
